apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: floatchat-db-pvc
  namespace: floatchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
