import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DotGrid from "@/components/ui/DotGrid/DotGrid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
        style={{ minHeight: "100vh", overflow: "hidden" }}
      >
        <div
          style={{
            position: "fixed",
            inset: 0,
            zIndex: 0,
            pointerEvents: "none",
          }}
        >
          <DotGrid
            baseColor="#878093"
            activeColor="#000000"
            dotSize={5}
            gap={70}
            proximity={110}
            shockRadius={200}
            shockStrength={10}
            resistance={750}
            returnDuration={1.5}
          />
        </div>

        <div style={{ position: "relative", zIndex: 1 }}>
          <a href="/auth" style={{ position: "absolute", top: 16, right: 16 }}>
            Auth
          </a>
          <a href="/me" style={{ position: "absolute", top: 16, right: 80 }}>
            Me
          </a>
          {children}
        </div>
      </body>
    </html>
  );
}
